const Discord = require('discord.js')
const client = new Discord.Client()
const allCards = []
function CardData(cost, text, type, name, set, attribute, B, Dmg, Core1, Core2)
{
this.cost = cost 
this.text = text 
this.type = type 
this.name = name 
this.set = set 
this.attribute = attribute 
this.B = B 
this.Dmg = Dmg 
this.Core1 = Core1 
this.Core2 = Core2 
}


allCards.push(new CardData(4,"Negate an Action card. You may copy its effect and make your own selections for it.","Action","Absorb","BB","Aquos")) 
allCards.push(new CardData(2,"+200 [B]. If [Aquos], draw a card.","Action","Aquos Shield","BB","Aquos")) 
allCards.push(new CardData(5,"+5 [Damage Rating]. Draw three cards.","Action","Aquos Slam","BB","Aquos")) 
allCards.push(new CardData(2,"+300 [B]. Retract your Bakugan at the end of the turn.","Action","Bubble Net","BB","Aquos")) 
allCards.push(new CardData(3,"Draw two cards, return this to the bottom of your deck.","Action","Cycling Thoughts","BB","Aquos")) 
allCards.push(new CardData(3,"Negate a Hero card.","Action","Deep Illusion","BB","Aquos")) 
allCards.push(new CardData(2,"+2 [Damage Rating]. Flow - If you played another card this turn, +5 [Damage Rating] instead.","Action","Ebb","BB","Aquos")) 
allCards.push(new CardData(2,"Retract a Bakugan that didn't open this turn.","Action","Fixation","BB","Aquos")) 
allCards.push(new CardData(1,"+200 [B] for each [Aquos] Bakugan on your team.","Action","Flooding Waters","BB","Aquos")) 
allCards.push(new CardData(0,"+100 [B].","Action","Greater Water Boost","BB","Aquos")) 
allCards.push(new CardData(3,"+200 [B]. Flow - If you played another card this turn, return this to your hand.","Action","Hurricane Slash","BB","Aquos")) 
allCards.push(new CardData(6,"+4 [Damage Rating and +4 [FrostStrike].","Action","Hydro Blast","BB","Aquos")) 
allCards.push(new CardData(2,"+400 [B].","Action","Ice Barrier","BB","Aquos")) 
allCards.push(new CardData(3,"+8 [Damage Rating] if you only have one open Bakugan.","Action","Ice Elation","BB","Aquos")) 
allCards.push(new CardData(3,"+6 [Damage Rating].","Action","Ice Sickle","BB","Aquos")) 
allCards.push(new CardData(4,"+900 [B].","Action","Ice Wall","BB","Aquos")) 
allCards.push(new CardData(1,"+1 [Damage Rating]. Draw a card.","Action","Inspire","BB","Aquos")) 
allCards.push(new CardData(2,"+3 [FrostStrike].","Action","Liquid Strike","BB","Aquos")) 
allCards.push(new CardData(2,"+2 [Damage Rating]. +2 [Damage Rating] for every other card you played this turn.","Action","Mind Flood","BB","Aquos")) 
allCards.push(new CardData(2,"+1 [Damage Rating]. Return this to your hand.","Action","Shuryuken","BB","Aquos")) 
allCards.push(new CardData(3,"+1000 [B] if you only have one open Bakugan.","Action","Solitude","BB","Aquos")) 
allCards.push(new CardData(2,"Draw a card. Flow - If you played another card this turn, draw two cards instead.","Action","Think Again","BB","Aquos")) 
allCards.push(new CardData(4,"+7 [Damage Rating].","Action","Tidal Wave","BB","Aquos")) 
allCards.push(new CardData(1,"+200 [B]. Flow - If you played another card this turn, +400 [B] instead.","Action","Tides","BB","Aquos")) 
allCards.push(new CardData(3,"Negate an Action card.","Action","Triple Blast Cannon","BB","Aquos")) 
allCards.push(new CardData(1,"+2 [Damage Rating].","Action","Water Slash","BB","Aquos")) 
allCards.push(new CardData(3,"+300 [B]. Flow - If you played another card this turn, +1000 [B] instead.","Action","Wave Slash","BB","Aquos")) 
allCards.push(new CardData(3,"+3 [Damage Rating]. Flow - If you played another card this turn, +3 [FrostStrike].","Action","Whirlpool","BB","Aquos")) 
allCards.push(new CardData(1,"Choose a player to discard a card.","Action","Chaotic Darkness","BB","Darkus")) 
allCards.push(new CardData(2,"+3 [Damage Rating] and [ShadowStrike].","Action","Cloak in Shadow","BB","Darkus")) 
allCards.push(new CardData(4,"+100 [B] for each 1 [Damage Rating] your Bakugan has.","Action","Corrupting Mist","BB","Darkus")) 
allCards.push(new CardData(2,"-2 [Damage Rating]. Sacrifice - You may discard a card for -10 [Damage Rating] instead.","Action","Curse of Darkus","BB","Darkus")) 
allCards.push(new CardData(3,"You draw a card and your opponent discards a card, return this to the bottom of your deck.","Action","Cycling Madness","BB","Darkus")) 
allCards.push(new CardData(2,"+5 [Damage Rating].","Action","Dark Boost","BB","Darkus")) 
allCards.push(new CardData(4,"+9 [Damage Rating].","Action","Dark Fire","BB","Darkus")) 
allCards.push(new CardData(3,"+6 [Damage Rating]. If [Darkus], choose a player to discard a card.","Action","Darkus Strike","BB","Darkus")) 
allCards.push(new CardData(2,"Destroy a Hero with cost 4 [Energy] or less.","Action","Garganoid's Gaze","BB","Darkus")) 
allCards.push(new CardData(5,"Choose a Bakugan. Your opponent chooses if it gets +1000 [B] or +10 [Damage Rating].","Action","Gravity Shift","BB","Darkus")) 
allCards.push(new CardData(4,"Destroy a Hero.","Action","Hero's Demise","BB","Darkus")) 
allCards.push(new CardData(2,"+[ShadowStrike]. Sacrifice - You may discard a card for +5 [Damage Rating].","Action","Might of Night","BB","Darkus")) 
allCards.push(new CardData(4,"Draw a card. Sacrifice - You may discard a card for +3 [Damage Rating]. You may use this any number of times.","Action","Night Lightning","BB","Darkus")) 
allCards.push(new CardData(4,"+300 [B]. +6 [Damage Rating].","Action","Prismatic Bolt","BB","Darkus")) 
allCards.push(new CardData(1,"+200 [B].","Action","Prismatic Shield","BB","Darkus")) 
allCards.push(new CardData(5,"Choose a player to discard a card for each [Darkus] Bakugan on your team.","Action","Rite of Darkus","BB","Darkus")) 
allCards.push(new CardData(0,"+2 [Damage Rating].","Action","Shade Blade","BB","Darkus")) 
allCards.push(new CardData(3,"+4 [Damage Rating]. If this is discarded, you may play it for free.","Action","Shadow Coil","BB","Darkus")) 
allCards.push(new CardData(2,"+100 [B]. +3 [Damage Rating].","Action","Shadow Hue","BB","Darkus")) 
allCards.push(new CardData(5,"-3 [Damage Rating]. Sacrifice - You may discard a card for -3 [Damage Rating] for all enemy Bakugan instead.","Action","Shadow Trap","BB","Darkus")) 
allCards.push(new CardData(3,"+500 [B].","Action","Smoke Armor","BB","Darkus")) 
allCards.push(new CardData(3,"+200 [B]. Sacrifice - You may discard a card for +800 [B] instead.","Action","Stoneskin","BB","Darkus")) 
allCards.push(new CardData(3,"+300 [B]. Sacrifice - You may discard a card to return this to your hand.","Action","Storm Generator","BB","Darkus")) 
allCards.push(new CardData(2,"+2 [Damage Rating]. Sacrifice - You may discard a card for +7 [Damage Rating] instead.","Action","Tainted Touch","BB","Darkus")) 
allCards.push(new CardData(4,"-6 [Damage Rating].","Action","Terrify","BB","Darkus")) 
allCards.push(new CardData(4,"Choose a player to discard two cards.","Action","Thought Decay","BB","Darkus")) 
allCards.push(new CardData(2,"+100 [B] for each Flip card in your discard pile.","Action","Umbral Slash","BB","Darkus")) 
allCards.push(new CardData(5,"+900 [B].","Action","Unrivaled Jump","BB","Darkus")) 
allCards.push(new CardData(1,"-3 [Damage Rating].","Action","Wither","BB","Darkus")) 
allCards.push(new CardData(6,"+6 [Damage Rating]. Domination - If your Bakugan hold the most BakuCores, +12 [Damage Rating] instead.","Action","Beaming Blaster","BB","Haos")) 
allCards.push(new CardData(3,"-3 [Damage Rating] to an enemy Bakugan or +3 [Damage Rating] to one of your Bakugan.","Action","Blinding Glam","BB","Haos")) 
allCards.push(new CardData(2,"+1 [FrostStrike], then +1 [Damage Rating] for each point of [FrostStrike] that Bakugan has.","Action","Body Guard","BB","Haos")) 
allCards.push(new CardData(3,"+700 [B].","Action","Bone Defense","BB","Haos")) 
allCards.push(new CardData(3,"Attach a BakuCore from the Field to an open Bakugan.","Action","Consort","BB","Haos")) 
allCards.push(new CardData(4,"+500 [B]. Domination - If your Bakugan hold the most BakuCores, draw three cards.","Action","Cutepocalypse","BB","Haos")) 
allCards.push(new CardData(1,"+200 [B], then put this on the bottom of your deck.","Action","Cycling Light","BB","Haos")) 
allCards.push(new CardData(5,"+1100 [B].","Action","Dream Illusion","BB","Haos")) 
allCards.push(new CardData(2,"-5 [Damage Rating] to a non-[Haos] Bakugan.","Action","Fragile to Light","BB","Haos")) 
allCards.push(new CardData(5,"+9 [Damage Rating].","Action","Heroic Strength","BB","Haos")) 
allCards.push(new CardData(2,"+300 [B]. If [Haos], +600 [B] instead.","Action","Light Break","BB","Haos")) 
allCards.push(new CardData(2,"+400 [B]. Domination - if your Bakugan hold the most BakuCores, +800 [B] instead.","Action","Light's Courage","BB","Haos")) 
allCards.push(new CardData(4,"+900 [B] to a [Haos] Bakugan.","Action","Luminous Armor","BB","Haos")) 
allCards.push(new CardData(5,"+4 [Damage Rating] and draw a card.","Action","Pandoxx Punch","BB","Haos")) 
allCards.push(new CardData(1,"+1 [FrostStrike] for each [Haos] Bakugan on your team.","Action","Reflection Rays","BB","Haos")) 
allCards.push(new CardData(3,"+4 [Damage Rating] for each Hero you have in play.","Action","Revitalize","BB","Haos")) 
allCards.push(new CardData(3,"+5 [Damage Rating].","Action","Shine","BB","Haos")) 
allCards.push(new CardData(2,"Draw a card. Domination - If your Bakugan hold the most BakuCores, draw two cards instead.","Action","Stoic Shot","BB","Haos")) 
allCards.push(new CardData(1,"+300 [B].","Action","Super Shot","BB","Haos")) 
allCards.push(new CardData(2,"+4 [Damage Rating].","Action","Surge of Light","BB","Haos")) 
allCards.push(new CardData(1,"Look at the top three cards of your deck. Put them on top of your deck in any order. Domination - If your Bakugan hold the most BakuCores, draw a card.","Action","The Sky's Hymn","BB","Haos")) 
allCards.push(new CardData(2,"+2 [FrostStrike].","Action","Thunder Sword","BB","Haos")) 
allCards.push(new CardData(2,"Destroy an Evo that was not played this turn.","Action","Wane","BB","Haos")) 
allCards.push(new CardData(6,"Destroy all enemy Evos.","Action","Wax","BB","Haos")) 
allCards.push(new CardData(0,"+3 [Damage Rating] to a [Haos] Bakugan.","Action","Whiteout","BB","Haos")) 
allCards.push(new CardData(6,"+600 [B]. Domination - If your Bakugan hold the most BakuCores, return this to your hand.","Action","Wing Cutter","BB","Haos")) 
allCards.push(new CardData(5,"Destroy all enemy Heroes.","Action","Cinder Coil","BB","Pyrus")) 
allCards.push(new CardData(2,"+2 [Damage Rating], then return this to the bottom of your deck.","Action","Cycling Warmth","BB","Pyrus")) 
allCards.push(new CardData(2,"Shuffle any number of cards from your hand into your deck. +1 [Damage Rating] for each card shuffled.","Action","Cyndeus Stand","BB","Pyrus")) 
allCards.push(new CardData(2,"+4 [Damage Rating]. Fury - If you have no cards in hand, +[DoubleStrike].","Action","Drago's Fury","BB","Pyrus")) 
allCards.push(new CardData(5,"+400 [B]. +6 [Damage Rating].","Action","Engulfing Embers","BB","Pyrus")) 
allCards.push(new CardData(2,"+200 [B]. Fury - If you have no cards in hand, +600 [B] instead.","Action","Fierce Boost","BB","Pyrus")) 
allCards.push(new CardData(3,"+200 [B]. Fury - If you have no cards in hand, +8 [Damage Power].","Action","Fiery Rage","BB","Pyrus")) 
allCards.push(new CardData(2,"+400 [B].","Action","Fire Boost","BB","Pyrus")) 
allCards.push(new CardData(6,"+6 [Damage Rating]. Fury - If you have no cards in hand, +12 [Damage Rating] instead.","Action","Fire Vortex","BB","Pyrus")) 
allCards.push(new CardData(1,"+3 [Damage Rating].","Action","Fireball","BB","Pyrus")) 
allCards.push(new CardData(3,"+6 [Damage Rating]. Fury: If you have no cards in hand, return this card to your hand.","Action","Furious Blast","BB","Pyrus")) 
allCards.push(new CardData(2,"Remove an enemy Bakugan's BakuCore and negate its effect. You return the BakuCore onto the field face down.","Action","Hot Potato","BB","Pyrus")) 
allCards.push(new CardData(3,"+7 [Damage Rating].","Action","Impact Lazer","BB","Pyrus")) 
allCards.push(new CardData(6,"Destroy an enemy Energy card. Fury - If you have no cards in hand, destroy two Energy cards instead.","Action","Implosion","BB","Pyrus")) 
allCards.push(new CardData(1,"+2 [Damage Rating] for each [Pyrus] on your team.","Action","Inferno","BB","Pyrus")) 
allCards.push(new CardData(3,"+300 [B]. Remove all BakuCores enemy Bakugan hold and negate their effects.","Action","Inferno Wings","BB","Pyrus")) 
allCards.push(new CardData(6,"+900 [B].","Action","Lava Boost","BB","Pyrus")) 
allCards.push(new CardData(4,"+700 [B].","Action","Magma Boost","BB","Pyrus")) 
allCards.push(new CardData(3,"Destroy an Energy card.","Action","Meltdown","BB","Pyrus")) 
allCards.push(new CardData(5,"+11 [Damage Rating].","Action","Meteoric Lance","BB","Pyrus")) 
allCards.push(new CardData(2,"+1 [Damage Rating]. This turn, the Victor is decided by highest [Damage Rating] instead of [B].","Action","Might of Cyndeus","BB","Pyrus")) 
allCards.push(new CardData(4,"+2 [Damage Rating] and [DoubleStrike].","Action","Molten Helix","BB","Pyrus")) 
allCards.push(new CardData(1,"+1 [Energy] for each BakuCore that your Bakugan hold.","Action","Power Ritual","BB","Pyrus")) 
allCards.push(new CardData(2,"+3 [Damage Rating]. If [Pyrus], +6 [Damage Rating] instead.","Action","Pyrus Strike","BB","Pyrus")) 
allCards.push(new CardData(1,"Draw two cards, then discard two cards.","Action","Sifting Ashes","BB","Pyrus")) 
allCards.push(new CardData(3,"+5 [Energy].","Action","Song of Fire","BB","Pyrus")) 
allCards.push(new CardData(3,"+4 [Damage Rating]. If the Bakugan's [Damage Rating] becomes 10 or greater, draw a card.","Action","Talon Slash","BB","Pyrus")) 
allCards.push(new CardData(3,"A Bakugan's [B] becomes 1000.","Action","Cocoon Shield","BB","Ventus")) 
allCards.push(new CardData(6,"-1000 [B].","Action","Crushing Grasp","BB","Ventus")) 
allCards.push(new CardData(5,"-8 [Damage Rating], then return this to the bottom of your deck.","Action","Cycling Ichor","BB","Ventus")) 
allCards.push(new CardData(3,"-600 [B].","Action","Deafening Roar","BB","Ventus")) 
allCards.push(new CardData(0,"You may use any number of [Energy] to play this. For each [Energy] used, give a Bakugan +100 [B] or +1 [Damage Rating].","Action","Endless Growth","BB","Ventus")) 
allCards.push(new CardData(3,"-5 [Damage Rating]. Turbo - If you have the most Energy cards in play, draw a card.","Action","Envenom","BB","Ventus")) 
allCards.push(new CardData(5,"+1 [Damage Rating] for each Energy card you have.","Action","Invigoration Blast","BB","Ventus")) 
allCards.push(new CardData(6,"+10 [Damage Rating].","Action","Lazer Claw","BB","Ventus")) 
allCards.push(new CardData(4,"Energize the top card of your deck uncharged. Return this to your hand.","Action","Mulch","BB","Ventus")) 
allCards.push(new CardData(1,"Give a non-[Ventus] Bakugan -500 [B].","Action","Nature's Power","BB","Ventus")) 
allCards.push(new CardData(4,"-300 [B]. Turbo - If you have the most Energy cards in play, -900 [B] instead.","Action","Oaken Shield","BB","Ventus")) 
allCards.push(new CardData(2,"Choose a Hero. Its controller must Energize it.","Action","One with Nature","BB","Ventus")) 
allCards.push(new CardData(4,"-7 [Damage Rating]","Action","Paralyzing Potion","BB","Ventus")) 
allCards.push(new CardData(2,"-400 [B].","Action","Piercing Scream","BB","Ventus")) 
allCards.push(new CardData(3,"+2 [Damage Rating]. Turbo - If you have the most Energy cards in play, +7 [Damage Rating] instead.","Action","Razor Claws","BB","Ventus")) 
allCards.push(new CardData(3,"-200 [B]. Turbo - If you have the most Energy cards in play, return this to your hand.","Action","Recycling Boost","BB","Ventus")) 
allCards.push(new CardData(2,"-3 [Damage Rating] for each [Ventus] Bakugan on your team.","Action","Shell Shield","BB","Ventus")) 
allCards.push(new CardData(4,"+4 [Damage Rating]. Another Bakugan gets -300 [B].","Action","Shock and Awe","BB","Ventus")) 
allCards.push(new CardData(2,"+3 [Damage Rating].","Action","Smash","BB","Ventus")) 
allCards.push(new CardData(3,"+4 [Damage Rating]. If [Ventus], Energize this uncharged.","Action","Sonic Howl","BB","Ventus")) 
allCards.push(new CardData(7,"+10 [Damage Rating]. Turbo -If you have the most Energy cards in play, draw three cards.","Action","Stomping Quake","BB","Ventus")) 
allCards.push(new CardData(4,"+8 [Damage Rating].","Action","Strength of Maxotaur","BB","Ventus")) 
allCards.push(new CardData(0,"-3 [Damage Rating].","Action","Toxify","BB","Ventus")) 
allCards.push(new CardData(2,"Energize this uncharged.","Action","Turn to Energy","BB","Ventus")) 
allCards.push(new CardData(1,"-4 [Damage Rating].","Action","Venom Blast","BB","Ventus")) 
allCards.push(new CardData(3,"-4 [Damage Rating]. Turbo - If you have the most Energy cards in play -8 [Damage Rating] instead.","Action","Ventus Moonbeam","BB","Ventus")) 
allCards.push(new CardData(4,"-4 [Damage Rating]. Energize this uncharged.","Action","Wild Strike","BB","Ventus")) 
allCards.push(new CardData(4,"Draw all remaining damage from an attack. (Instead of flipping the cards into your discard pile, put them into your hand.)","Flip","Brain Geyser","BB","Aquos")) 
allCards.push(new CardData(1,"[Stop] [Haos] or [Pyrus].","Flip","Counter Aggression","BB","Aquos")) 
allCards.push(new CardData(0,"[Stop] [Aquos].","Flip","Counter Aquos","BB","Aquos")) 
allCards.push(new CardData(0,"[Stop] [Haos].","Flip","Counter Haos","BB","Aquos")) 
allCards.push(new CardData(3,"[Stop] non-[Aquos].","Flip","Counter Outsiders","BB","Aquos")) 
allCards.push(new CardData(0,"[Stop] [Pyrus].","Flip","Counter Pyrus","BB","Aquos")) 
allCards.push(new CardData(1,"Draw a card.","Flip","Exhilarate","BB","Aquos")) 
allCards.push(new CardData(1,"Retract one of your Bakugan that didn't open this turn. If you do, draw two cards.","Flip","Fading Dash","BB","Aquos")) 
allCards.push(new CardData(3,"End the turn. Nothing else can happen this turn, start the next turn. (Cards cannot be played, remaining damage vanishes, and Energy Cards do not recharge.)","Flip","Blackhole","BB","Darkus")) 
allCards.push(new CardData(0,"[Stop] [Darkus].","Flip","Cease Darkus","BB","Darkus")) 
allCards.push(new CardData(0,"[Stop] [Haos].","Flip","Cease Haos","BB","Darkus")) 
allCards.push(new CardData(3,"[Stop] non-[Darkus].","Flip","Cease Outsiders","BB","Darkus")) 
allCards.push(new CardData(1,"[Stop] [Haos] or [Ventus].","Flip","Cease Serenity","BB","Darkus")) 
allCards.push(new CardData(0,"[Stop] [Ventus].","Flip","Cease Ventus","BB","Darkus")) 
allCards.push(new CardData(4,"[Stop] non-[Darkus]. Sacrifice - You may discard a card to play this for free.","Flip","Pact of Darkness","BB","Darkus")) 
allCards.push(new CardData(2,"Choose a player to discard a card.","Flip","Punish","BB","Darkus")) 
allCards.push(new CardData(4,"Take control of a Hero.","Flip","Shadow Breath","BB","Darkus")) 
allCards.push(new CardData(0,"[Stop] [Aquos].","Flip","Halt Aquos","BB","Haos")) 
allCards.push(new CardData(0,"[Stop] [Darkus].","Flip","Halt Darkus","BB","Haos")) 
allCards.push(new CardData(0,"[Stop] [Haos].","Flip","Halt Haos","BB","Haos")) 
allCards.push(new CardData(3,"[Stop] non-[Haos].","Flip","Halt Outsiders","BB","Haos")) 
allCards.push(new CardData(1,"[Stop] [Darkus] or [Aquos].","Flip","Halt Unknown","BB","Haos")) 
allCards.push(new CardData(5,"[Stop] non-[Haos], then put this into your hand.","Flip","Haos Ascendancy","BB","Haos")) 
allCards.push(new CardData(2,"Draw a card for each Hero you have in play.","Flip","Heroic Inspiration","BB","Haos")) 
allCards.push(new CardData(3,"Put this into your hand and draw a card.","Flip","Light as a Feather","BB","Haos")) 
allCards.push(new CardData(4,"Play a card from your hand for free.","Flip","Luck Aura","BB","Haos")) 
allCards.push(new CardData(1,"Put this into your hand.","Flip","Razor Wings","BB","Haos")) 
allCards.push(new CardData(4,"[Stop] non-[Haos]. Domination - If your Bakugan are holding the most BakuCores, this is free.","Flip","Stand Together","BB","Haos")) 
allCards.push(new CardData(0,"[Stop] [Aquos].","Flip","Block Aquos","BB","Pyrus")) 
allCards.push(new CardData(1,"[Stop] [Aquos] or [Ventus].","Flip","Block Growth","BB","Pyrus")) 
allCards.push(new CardData(3,"[Stop] non-[Pyrus].","Flip","Block Outsiders","BB","Pyrus")) 
allCards.push(new CardData(0,"[Stop] [Pyrus].","Flip","Block Pyrus","BB","Pyrus")) 
allCards.push(new CardData(0,"[Stop] [Ventus].","Flip","Block Ventus","BB","Pyrus")) 
allCards.push(new CardData(4,"[Stop] non-[Pyrus]. Fury - If you have no cards in hand, this is free.","Flip","Fierce Termination","BB","Pyrus")) 
allCards.push(new CardData(0,"+1 [Energy].","Flip","Lava Flow","BB","Pyrus")) 
allCards.push(new CardData(5,"[Stop] non-[Pyrus] and destroy an Energy card.","Flip","Pyrus Dominance","BB","Pyrus")) 
allCards.push(new CardData(1,"Draw a card, then discard a card.","Flip","Spark","BB","Pyrus")) 
allCards.push(new CardData(3,"Each player may energize the top two cards of their deck.","Flip","Hyperdrive","BB","Ventus")) 
allCards.push(new CardData(5,"[Stop] an attack and energize this uncharged.","Flip","Nature Assimilation","BB","Ventus")) 
allCards.push(new CardData(2,"Energize this uncharged.","Flip","Photosynthesis","BB","Ventus")) 
allCards.push(new CardData(0,"[Stop] [Darkus].","Flip","Repel Darkus","BB","Ventus")) 
allCards.push(new CardData(1,"[Stop] [Darkus] or [Pyrus].","Flip","Repel Destruction","BB","Ventus")) 
allCards.push(new CardData(3,"[Stop] non-[Ventus].","Flip","Repel Outsiders","BB","Ventus")) 
allCards.push(new CardData(0,"[Stop] [Pyrus].","Flip","Repel Pyrus","BB","Ventus")) 
allCards.push(new CardData(0,"[Stop] [Ventus]","Flip","Repel Ventus","BB","Ventus")) 
allCards.push(new CardData(3,"Turbo - If you have the most Energy cards in play, draw two cards.","Flip","Sowing Seeds","BB","Ventus")) 
allCards.push(new CardData(4,"[Stop] non-[Ventus]. Turbo - If you have the most Energy cards in play, this is free.","Flip","Tiger Reflex","BB","Ventus")) 
allCards.push(new CardData(5,"Energize this and the top card of your deck uncharged.","Flip","Trox's Moxy","BB","Ventus")) 
allCards.push(new CardData(4,"[Stop] non-[Ventus] and draw a card.","Flip","Ventus Power","BB","Ventus")) 
allCards.push(new CardData(1,"When you select a Bakugan to roll, you may turn a BakuCore on the field face up.","Hero","BEE","BB","Aquos")) 
allCards.push(new CardData(6,"This costs 2 [Energy] less to play for each card you have played this turn. Your Bakugan have +200 [B].","Hero","Everett Ray","BB","Aquos")) 
allCards.push(new CardData(5,"Your [Aquos] Bakugan have +2 [FrostStrike].","Hero","Maggie","BB","Aquos")) 
allCards.push(new CardData(1,"If you have played two or more cards this turn, your next attack this turn has +2 [Damage Rating].","Hero","Masato Kazami","BB","Aquos")) 
allCards.push(new CardData(2,"Evos cost you 1 [Energy] less to play.","Hero","Shun Kazami","BB","Aquos")) 
allCards.push(new CardData(2,"All players draw an additional card each turn.","Hero","Strata","BB","Aquos")) 
allCards.push(new CardData(9,"When you play this, search your deck for an Action card and reveal it, then put it into your hand. Shuffle your deck. Copy the first Action card you play each turn.","Hero","Toshi","BB","Aquos")) 
allCards.push(new CardData(4,"When you discard a card, a Bakugan gets +200 [B] and +2 [Damage Rating].","Hero","Benton Dusk","BB","Darkus")) 
allCards.push(new CardData(2,"+[ShadowStrike] to your [Darkus] Bakugan. If you deal 10 or more damage in an attack, you may draw three cards.","Hero","CEE","BB","Darkus")) 
allCards.push(new CardData(4,"+1 [Damage Rating] to your attacks. If this is discarded, you may play it for free.","Hero","China Riot","BB","Darkus")) 
allCards.push(new CardData(2,"When you play a Flip card, you may draw a card","Hero","Kurin","BB","Darkus")) 
allCards.push(new CardData(2,"Flip cards cost you 1 [Energy] less to play.","Hero","Lightning","BB","Darkus")) 
allCards.push(new CardData(8,"When you play this, a Bakugan gets +5000 [B]. Victor - You may discard a card to give a Bakugan +[Damage Rating] equal to the discarded card's Energy cost.","Hero","Magnus","BB","Darkus")) 
allCards.push(new CardData(3,"When one of your Bakugan attacks, draw a card.","Hero","Col. Armstrong Tripp","BB","Haos")) 
allCards.push(new CardData(4,"Your Bakugan have +1 [FrostStrike].","Hero","DEE","BB","Haos")) 
allCards.push(new CardData(10,"When you play this, search your deck for a Hero card and reveal it, then put it into your hand. Shuffle your deck. +10 [Damage Rating] to your attacks, if you control five or more Hero cards in play.","Hero","Lia Venegas","BB","Haos")) 
allCards.push(new CardData(6,"Domination - If your Bakugan are holding the most BakuCores, this costs 3 [Energy] less to play. +200 [B] to your Bakugan.","Hero","Philomena Dusk","BB","Haos")) 
allCards.push(new CardData(3,"Domination - If your Bakugan are holding the most BakuCores, +3 [Damage Rating] to your attacks.","Hero","Veronica Venegas","BB","Haos")) 
allCards.push(new CardData(3,"Fury - At the end of the turn, if you have no cards in hand, draw a card.","Hero","Barbara Kouzo","BB","Pyrus")) 
allCards.push(new CardData(2,"When an opponent plays a Flip card, you may draw a card.","Hero","Bill Kouzo","BB","Pyrus")) 
allCards.push(new CardData(4,"When you open a Bakugan, reveal the top card of your deck. If its not a Flip card, you may play it for free.","Hero","Dan Kouzo","BB","Pyrus")) 
allCards.push(new CardData(11,"When you play this, it makes a [Pyrus] attack for 5 [Damage Rating]. +[DoubleStrike] to your Bakugan.","Hero","Duran Dane","BB","Pyrus")) 
allCards.push(new CardData(5,"When you open a Bakugan, +3 [Energy] for the turn.","Hero","E","BB","Pyrus")) 
allCards.push(new CardData(4,"The turn you play this, the Victor is decided by highest [Damage Rating] instead of [B]. Your Bakugan have +2 [Damage Rating].","Hero","Mac","BB","Pyrus")) 
allCards.push(new CardData(3,"Fury - If you have no cards in hand, +5 [Damage Rating] to your attacks.","Hero","Marco","BB","Pyrus")) 
allCards.push(new CardData(6,"Turbo - If you have the most Energy cards in play, your attacks have +4 [Damage Rating].","Hero","AAY","BB","Ventus")) 
allCards.push(new CardData(9,"Opposing Bakugan get -3 [Damage Rating]. If you take damage, destroy this.","Hero","Max","BB","Ventus")) 
allCards.push(new CardData(6,"Non-[Ventus] Bakugan get -300 [B].","Hero","Olivia Styles","BB","Ventus")) 
allCards.push(new CardData(4,"When you open a Bakugan, you may Energize the top card of your deck. If you have 15 or more Energy cards in play, your Bakugan have +1500 [B].","Hero","Wynton Styles","BB","Ventus")) 
allCards.push(new CardData(1,"Swap the BakuCore attached to the Bakugan you rolled this turn and the opposing Bakugan.","Action","Aquify","BR","Aquos")) 
allCards.push(new CardData(5,"+1200 [B].","Action","Aquos Splash","BR","Aquos")) 
allCards.push(new CardData(2,"Negate an Action card that costs 3 [Energy] or less.","Action","Blinding Ink","BR","Aquos")) 
allCards.push(new CardData(2,"+4 [Damage Rating].","Action","Claw Cutter","BR","Aquos")) 
allCards.push(new CardData(1,"+200 [B] and you may Reroll your Bakugan.","Action","Dark Waters","BR","Aquos")) 
allCards.push(new CardData(1,"Draw a card and you may Reroll your Bakugan.","Action","Deep Dive","BR","Aquos")) 
allCards.push(new CardData(3,"+300 [B]. You can play an Action card that costs 4 [Energy] or less for free.","Action","Hurricane Winds","BR","Aquos")) 
allCards.push(new CardData(4,"+400 [B]. Flow: If you played another card this turn, +4 [FrostStrike].","Action","Mud Pit","BR","Aquos")) 
allCards.push(new CardData(4,"You must Reroll your Bakugan. If you open on the Reroll, your Bakugan gets +500 [B] and you may draw two cards.","Action","Rip Tide","BR","Aquos")) 
allCards.push(new CardData(6,"For the rest of the turn, both players may play Evo cards from their hand for free.","Action","Sneak Attack","BR","Aquos")) 
allCards.push(new CardData(3,"+600 [B]. If that Bakugan is holding [FT], +2 [FrostStrike].","Action","Unstoppable","BR","Aquos")) 
allCards.push(new CardData(3,"+5 [Damage Rating]. If that Bakugan is holding [SD], draw a card.","Action","Water to Ice","BR","Aquos")) 
allCards.push(new CardData(3,"Search your deck for an Evo card, reveal it and put it in your hand. Then shuffle your deck.","Action","Dark Fortune","BR","Darkus")) 
allCards.push(new CardData(2,"+300 [B].","Action","Dark Path","BR","Darkus")) 
allCards.push(new CardData(4,"+400 [B]. Sacrifice: You may discard a card for +1000 [B] instead.","Action","Darkus Howl","BR","Darkus")) 
allCards.push(new CardData(2,"-5 [Damage Rating].","Action","Darkus Petrify","BR","Darkus")) 
allCards.push(new CardData(1,"+200 [B]. If that Bakugan is holding [FT], +3 [Damage Rating].","Action","Darkus Slicer","BR","Darkus")) 
allCards.push(new CardData(3,"+300 [B]. Sacrifice: You may discard a card to draw two cards.","Action","Dust to Dust","BR","Darkus")) 
allCards.push(new CardData(5,"Your opponent reveals their hand. You may play an Action card from it for free, gain its effect, and put it in your opponent's discard pile.","Action","Mind Control","BR","Darkus")) 
allCards.push(new CardData(2,"Choose a player to discard a card and you may Reroll your Bakugan.","Action","Mind Slip","BR","Darkus")) 
allCards.push(new CardData(3,"+300 [B], +4 [Damage Rating], and you may Reroll your Bakugan.","Action","Second Strike","BR","Darkus")) 
allCards.push(new CardData(5,"+10 [Damage Rating]. If that Bakugan is holding [SD], +[ShadowStrike].","Action","Shadow Cloak","BR","Darkus")) 
allCards.push(new CardData(4,"You must Reroll your Bakugan. If you open on the Reroll, that Bakugan gets +400 [B] and Victor: An opponent must discard 2 cards.","Action","Shadow Dogs","BR","Darkus")) 
allCards.push(new CardData(1,"+3 [Damage Rating].","Action","Thunder Bolt","BR","Darkus")) 
allCards.push(new CardData(2,"+200 [B] for each Hero card you have in play.","Action","Blinding Light","BR","Haos")) 
allCards.push(new CardData(4,"+7 [Damage Rating].","Action","Divine Inspriation","BR","Haos")) 
allCards.push(new CardData(4,"You must Reroll your Bakugan. If you open on the Reroll, you may play that Bakugan's Evo card for free.","Action","Divine Intervention","BR","Haos")) 
allCards.push(new CardData(2,"+500 [B].","Action","Energy Draw","BR","Haos")) 
allCards.push(new CardData(2,"+4 [Damage Rating] and you may Reroll your Bakugan.","Action","Haos Blessing","BR","Haos")) 
allCards.push(new CardData(3,"+400 [B] and you may Reroll your Bakugan.","Action","Spirit Guide","BR","Haos")) 
allCards.push(new CardData(1,"+300 [B]. If that Bakugan is holding [FT], +600 [B] instead.","Action","Holy Flame","BR","Haos")) 
allCards.push(new CardData(3,"+3 [FrostStrike] to a [Haos] Bakugan.","Action","Karmic Balance","BR","Haos")) 
allCards.push(new CardData(1,"Attach a [FT] from the field to an open Bakugan.","Action","Mega Punch","BR","Haos")) 
allCards.push(new CardData(4,"Draw two cards. Domination: If your Bakugan hold the most BakuCores, +5 [DamageRating] and +2 [FrostStrike].","Action","Pegatrix Drill","BR","Haos")) 
allCards.push(new CardData(5,"+9 [Damage Rating]. If that Bakugan is holding [SD], draw two cards.","Action","Shield of the Faithful","BR","Haos")) 
allCards.push(new CardData(2,"Reveal the top card of your deck. If it is not a Flip card, you may play it for free.","Action","Air Zero","BR","Pyrus")) 
allCards.push(new CardData(2,"+300 [B]. Fury: If you have no cards in hand, draw two cards.","Action","Anger","BR","Pyrus")) 
allCards.push(new CardData(4,"+10 [Damage Rating].","Action","Blaze","BR","Pyrus")) 
allCards.push(new CardData(6,"+20 [Damage Rating].","Action","Boom","BR","Pyrus")) 
allCards.push(new CardData(3,"+[DoubleStrike] and you may Reroll your Bakugan.","Action","Dual Strike","BR","Pyrus")) 
allCards.push(new CardData(3,"+600 [B].","Action","Flame Wave","BR","Pyrus")) 
allCards.push(new CardData(3,"+3 [Damage Rating]. If that Bakugan is holding [SD], +[DoubleStrike].","Action","Magma Shield","BR","Pyrus")) 
allCards.push(new CardData(3,"+400 [B]. Fury: If you have no cards in your hand, +8 [Damage Rating].","Action","Pyrus Heat Shield","BR","Pyrus")) 
allCards.push(new CardData(0,"Make a [Pyrus] attack for 1 [Damage Rating] and you may Reroll your Bakugan.","Action","Quickfire","BR","Pyrus")) 
allCards.push(new CardData(1,"You must Reroll your Bakugan. If you open on the Reroll, the next card you play this turn costs 3 [Energy] less.","Action","Superfuel","BR","Pyrus")) 
allCards.push(new CardData(2,"+4 [Damage Rating]. If your Bakugan is holding [FT], +8 [Damage Rating] instead.","Action","Sword Barrage","BR","Pyrus")) 
allCards.push(new CardData(3,"Remove an enemy Bakugan's BakuCore and negate its effects. You place the BakuCore onto the field face down. If one of your Bakugan are holding [FT], draw a card.","Action","Twisting Inferno","BR","Pyrus")) 
allCards.push(new CardData(4,"Draw two cards. Turbo: If you have the most Energy cards in play, give an opposing Bakugan -700 [B].","Action","Crystal Quake","BR","Ventus")) 
allCards.push(new CardData(1,"-200 [B]. Turbo: If you have the most Energy cards in play, -400 [B] instead.","Action","Etropic Blast","BR","Ventus")) 
allCards.push(new CardData(10,"Energize each card in your discard pile uncharged.","Action","Huge Knowledge","BR","Ventus")) 
allCards.push(new CardData(5,"You must Reroll your Bakugan. If you open on the Reroll, that Bakugan gets +10 [Damage Rating] and [ShadowStrike].","Action","Nature's Blessing","BR","Ventus")) 
allCards.push(new CardData(4,"+4 [Damage Rating]. Recharge your Energy cards.","Action","Rabid Attack","BR","Ventus")) 
allCards.push(new CardData(1,"+2 [Damage Rating].","Action","Shatterfist","BR","Ventus")) 
allCards.push(new CardData(3,"Energize this uncharged and you may Reroll your Bakugan.","Action","Solar Powered","BR","Ventus")) 
allCards.push(new CardData(1,"+2 [Damage Rating]. If your Bakugan is holding [FT], Energize this card uncharged.","Action","Stoneblade","BR","Ventus")) 
allCards.push(new CardData(4,"-800 [B] to the opposing Bakugan and you may Reroll your Bakugan.","Action","Tanglevines","BR","Ventus")) 
allCards.push(new CardData(3,"-6 [Damage Rating]. If your Bakugan is holding [SD], draw a card.","Action","Tremor","BR","Ventus")) 
allCards.push(new CardData(2,"-200 [B] and -2 [Damage Rating].","Action","Ventus Shield","BR","Ventus")) 
allCards.push(new CardData(2,"The opposing Bakugan must Reroll.","Action","Ventus Mirage","BR","Ventus")) 
allCards.push(new CardData(1,"[Stop] a Bakugan holding [SD] or [HE].","Flip","Deep Freeze","BR","Aquos")) 
allCards.push(new CardData(0,"[Stop] a Bakugan holding [FT].","Flip","Freeze","BR","Aquos")) 
allCards.push(new CardData(2,"Flip a coin. If heads, stop the attack.","Flip","Lost at Sea","BR","Aquos")) 
allCards.push(new CardData(2,"Choose a non-Energy card in play and return it to its owner's hand.","Flip","Flash Flood","BR","Aquos")) 
allCards.push(new CardData(0,"[Stop] a Bakugan holding [MS].","Flip","Darkus Snare","BR","Darkus")) 
allCards.push(new CardData(2,"Your opponent reveals his or her hand and you choose an Action card. They must discard it.","Flip","Darkus Blitz","BR","Darkus")) 
allCards.push(new CardData(1,"[Stop] a Bakugan holding [FF] or [FT].","Flip","Sonic Shield","BR","Darkus")) 
allCards.push(new CardData(1,"[Stop] a Bakugan holding [FF] or [MS].","Flip","Confuse","BR","Haos")) 
allCards.push(new CardData(0,"[Stop] a Bakugan holding [HE].","Flip","Dazzle","BR","Haos")) 
allCards.push(new CardData(4,"Destroy an Evo card.","Flip","Haos Curse","BR","Haos")) 
allCards.push(new CardData(0,"Play a Hero that costs 3 [Energy] or less for free.","Flip","Trick Trap","BR","Haos")) 
allCards.push(new CardData(0,"[Stop] a Bakugan holding [SD].","Flip","Ash Cloud","BR","Pyrus")) 
allCards.push(new CardData(1,"[Stop] a Bakugan holding [FT] or [HE].","Flip","Constrictor","BR","Pyrus")) 
allCards.push(new CardData(4,"Make a [Pyrus] attack for 4 [Damage Rating].","Flip","Spontaneous Combustion","BR","Pyrus")) 
allCards.push(new CardData(1,"[Stop] a Bakugan holding [MS] or [SD].","Flip","Rock Riser","BR","Ventus")) 
allCards.push(new CardData(1,"Recharge your Energy cards.","Flip","Ruin","BR","Ventus")) 
allCards.push(new CardData(0,"[Stop] a Bakugan holding [FF].","Flip","Web Snare","BR","Ventus")) 
allCards.push(new CardData(3,"When you open a Bakugan, draw a card.","Hero","Shun Kazami","BR","Aquos")) 
allCards.push(new CardData(2,"When you open a Bakugan, it gets +3 [Damage Rating].","Hero","Lightning","BR","Darkus")) 
allCards.push(new CardData(1,"When you open a Bakugan, it gets +100 [B].","Hero","Shargo Ronin","BR","Haos")) 
allCards.push(new CardData(3,"Your Hero cards cost 2 [Energy] less.","Hero","Strata","BR","Haos")) 
allCards.push(new CardData(4,"Your Bakugan get [DoubleStrike].","Hero","Dan Kouzo","BR","Pyrus")) 
allCards.push(new CardData(6,"When you open a Bakugan, make a [Pyrus] attack for 2 [DamageRating].","Hero","Emily","BR","Pyrus")) 
allCards.push(new CardData(2,"Fury: At the end of the turn, if you have no cards in hand, make a [Pyrus] attack for 2 [Damage Rating].","Hero","Jenkins","BR","Pyrus")) 
allCards.push(new CardData(3,"When you open a Bakugan, you may Energize a card from your hand uncharged.","Hero","China Riot","BR","Ventus")) 
allCards.push(new CardData(4,"","Evo","[Diamond] Hydranoid","BR","Aquos",600,12)) 
allCards.push(new CardData(8,"","Evo","[Diamond] Hydranoid Ultra","BR","Aquos",1900,8)) 
allCards.push(new CardData(7,"7 [FrostStrike].","Evo","[Diamond] Serpenteze Ultra","BR","Aquos",700,7)) 
allCards.push(new CardData(3,"Victor: Draw a card.","Evo","Hyper Gorthion","BR","Aquos",900,3)) 
allCards.push(new CardData(2,"[FT]: +300 [B]. When you play this, give a Bakugan +2 [Damage Rating] and +2 [FrostStrike].","Evo","Hyper Krakelios Ultra","BR","Aquos",700,4)) 
allCards.push(new CardData(2,"When this opens, you may swap one of this Bakugan's BakuCores with the opposing Bakugan.","Evo","Hyper Mantonoid","BR","Aquos",700,4)) 
allCards.push(new CardData(2,"[SD]: +3 [Damage Rating]. [FT]: +300 [B].","Evo","Hyper Serpeteze","BR","Aquos",500,5)) 
allCards.push(new CardData(4,"[FT]: +400 [B] and +5 [Damage Rating]. You may Reroll this once each turn if you miss a Roll with it.","Evo","Hyper Trox Ultra","BR","Aquos",700,7)) 
allCards.push(new CardData(3,"[SD]: +4 [FrostStrike].","Evo","Hyper Turtonium","BR","Aquos",800,4)) 
allCards.push(new CardData(2,"[HE]: +200 [B] and +4 [Damage Rating]. You may Reroll this once each turn if you miss a Roll with it.","Evo","Hyper Turtonium Ultra","BR","Aquos",800,4)) 
allCards.push(new CardData(5,"3 [FrostStrike]. If you play two or more cards this turn, +5 [Damage Rating].","Evo","Titan Cyndeous Ultra","BR","Aquos",1000,5)) 
allCards.push(new CardData(5,"[MS]: +200 [B] and +2 [FrostStrike]. You may Reroll this once each turn if you miss a Roll with it.","Evo","Titan Nillious","BR","Aquos",900,8)) 
allCards.push(new CardData(4,"Victor: Reveal the top card of your deck. This gets +[DamageRating] equal to twice the revealed card's [Energy] cost.","Evo","Titan Pegatrix Ultra","BR","Aquos",1000,6)) 
allCards.push(new CardData(1,"","Evo","Hyper Hydorous Ultra","BR","Aurelus",800,6)) 
allCards.push(new CardData(2,"You may Reroll this once each turn if you miss a Roll with it.","Evo","Hyper Mantonoid","BR","Aurelus",800,5)) 
allCards.push(new CardData(3,"","Evo","Hyper Serpenteze","BR","Aurelus",900,7)) 
allCards.push(new CardData(2,"[ShadowStrike]. When you play an Action on this, this gets +300 [B] and +4 [Damage Rating].","Evo","Hyper Trox","BR","Aurelus",600,6)) 
allCards.push(new CardData(10,"If there are 20 or more cards in your discard pile, you may play this for free.","Evo","Maximus Fangzor Ultra","BR","Aurelus",1500,10)) 
allCards.push(new CardData(7,"","Evo","Maximus Trox Ultra","BR","Aurelus",1200,15)) 
allCards.push(new CardData(4,"This counts as all Factions.","Evo","Titan Dragonoid Ultra","BR","Aurelus",1200,10)) 
allCards.push(new CardData(5,"When you play this, give a Bakugan +400 [B] and +4 [DamageRating].","Evo","Titan Gorthion","BR","Aurelus",1000,6)) 
allCards.push(new CardData(5,"You may Reroll this once each turn if you miss a Roll with it. Victor: Choose one: Energize the top two cards of your deck uncharged, or draw two cards.","Evo","Titan Krakelios Ultra","BR","Aurelus",1100,5)) 
allCards.push(new CardData(4,"[MS]: +[ShadowStrike]. [FF]: +3 [FrostStrike].","Evo","Titan Turtonium","BR","Aurelus",600,10)) 
allCards.push(new CardData(4,"","Evo","[Diamond] Phaedrus","BR","Darkus",700,9)) 
allCards.push(new CardData(4,"Victor: Your opponent discards a card.","Evo","Hyper Cyndeous Ultra","BR","Darkus",900,5)) 
allCards.push(new CardData(2,"[FT]: +400 [B] and +3 [Damage Rating].","Evo","Hyper Dragonoid Ultra","BR","Darkus",500,5)) 
allCards.push(new CardData(3,"[ShadowStrike].","Evo","Hyper Fangzor Ultra","BR","Darkus",1000,3)) 
allCards.push(new CardData(1,"Victor: You may discard a Flip card for +4 [Damage Rating].","Evo","Hyper Gorthion Ultra","BR","Darkus",500,4)) 
allCards.push(new CardData(3,"[SD]: +800 [B].","Evo","Hyper Nillious Ultra","BR","Darkus",500,8)) 
allCards.push(new CardData(2,"You may Reroll this once each turn if you miss a Roll with it.","Evo","Hyper Pegatrix","BR","Darkus",500,9)) 
allCards.push(new CardData(3,"When you play this, give a Bakugan +400 [B] and [ShadowStrike].","Evo","Hyper Serpenteze Ultra","BR","Darkus",600,8)) 
allCards.push(new CardData(8,"You may Reroll this once each turn if you miss a Roll with it. You can play this from your discard pile as though it were in your hand.","Evo","Maximus Garganoid Ultra","BR","Darkus",1000,10)) 
allCards.push(new CardData(5,"","Evo","Titan Cyndeous","BR","Darkus",1000,10)) 
allCards.push(new CardData(6,"You may Reroll this once each turn if you miss a Roll with it.","Evo","Titan Mantonoid","BR","Darkus",800,12)) 
allCards.push(new CardData(5,"[FF]: +500 [B] and +6 [Damage Rating]. You may Reroll this once each turn if you miss a Roll with it.","Evo","Titan Serpenteze","BR","Darkus",900,7)) 
allCards.push(new CardData(4,"When you play this, you must discard your hand.","Evo","Titan Turtonium Ultra","BR","Darkus",1000,15)) 
allCards.push(new CardData(6,"","Evo","[Diamond] Cubbo","BR","Haos",700,10)) 
allCards.push(new CardData(5,"","Evo","[Diamond] Gorthion","BR","Haos",400,13)) 
allCards.push(new CardData(5,"If this has two or more BakuCores attached to it, +1000 [B].","Evo","[Diamond] Pegatrix Ultra","BR","Haos",1000,10)) 
allCards.push(new CardData(2,"When you play this, give a Bakugan +300 [B].","Evo","Hyper Dragonoid","BR","Haos",700,4)) 
allCards.push(new CardData(3,"2 [FrostStrike].","Evo","Hyper Hydorous","BR","Haos",600,6)) 
allCards.push(new CardData(2,"If this has two or more BakuCores attached to it, +500 [B].","Evo","Hyper Pegatrix Ultra","BR","Haos",500,7)) 
allCards.push(new CardData(1,"If this has two or more BakuCores attached to it, +10 [DamageRating].","Evo","Hyper Serpenteze","BR","Haos",600,4)) 
allCards.push(new CardData(6,"If you have three or more Hero cards in play, you may play this for free.","Evo","Maximus Mantonoid Ultra","BR","Haos",1100,8)) 
allCards.push(new CardData(7,"When you play this, you may play a Hero for free.","Evo","Maximus Maxotaur Ultra","BR","Haos",1300,10)) 
allCards.push(new CardData(6,"When you play this, destroy all other Evos.","Evo","Titan Gorthion Ultra","BR","Haos",1200,4)) 
allCards.push(new CardData(4,"","Evo","Titan Krakelios Ultra","BR","Haos",800,8)) 
allCards.push(new CardData(4,"You may Reroll this once each turn if you miss a roll with it.","Evo","Titan Mantonoid","BR","Haos",900,5)) 
allCards.push(new CardData(6,"Domination: If your Bakugan are holding the most BakuCores, this costs 3 [Energy] less to use.","Evo","Titan Nillious Ultra","BR","Haos",1100,7)) 
allCards.push(new CardData(6,"[MS]: +5 [FrostStrike].","Evo","Titan Trox","BR","Haos",1000,8)) 
allCards.push(new CardData(6,"","Evo","[Diamond] Cyndeous","BR","Pyrus",700,12)) 
allCards.push(new CardData(4,"[SD]: +4 [Damage Rating].","Evo","[Diamond] Cyndeous Ultra","BR","Pyrus",1000,4)) 
allCards.push(new CardData(9,"Fury: If you have no cards in hand, +[DoubleStrike].","Evo","[Diamond] Dragonoid Ultra","BR","Pyrus",1800,12)) 
allCards.push(new CardData(2,"","Evo","Hyper Dragonoid Ultra","BR","Pyrus",800,8)) 
allCards.push(new CardData(3,"","Evo","Hyper Fangzor Ultra","BR","Pyrus",600,10)) 
allCards.push(new CardData(4,"Victor: Draw cards until you have as many as your opponent.","Evo","Hyper Garganoid Ultra","BR","Pyrus",800,8)) 
allCards.push(new CardData(2,"FT: +200 [B] and +4 [Damage Rating]. You may Reroll this once each turn if you miss a Roll with it.","Evo","Hyper Gorthion","BR","Pyrus",400,6)) 
allCards.push(new CardData(2,"","Evo","Hyper Mantonoid","BR","Pyrus",700,3)) 
allCards.push(new CardData(4,"You may Reroll this once each turn if you miss a Roll with it.","Evo","Hyper Pegatrix","BR","Pyrus",800,10)) 
allCards.push(new CardData(5,"When this opens, if it is holding a [FF], make a [Pyrus] attack for 5 [Damage Rating].","Evo","Hyper Serpenteze","BR","Pyrus",1000,1)) 
allCards.push(new CardData(1,"When you play this, give a Bakugan +3 [Damage Rating].","Evo","Hyper Trox Ultra","BR","Pyrus",500,3)) 
allCards.push(new CardData(8,"You may Reroll this once each turn if you miss a Roll with it. When this opens, if it is holding a [FF], you may destroy an Energy card.","Evo","Maximus Turtonium Ultra","BR","Pyrus",1500,3)) 
allCards.push(new CardData(5,"","Evo","Titan Gorthion Ultra","BR","Pyrus",1400,6)) 
allCards.push(new CardData(5,"When you play this, give a Bakugan +1 [Damage Rating] and [DoubleStrike].","Evo","Titan Trox Ultra","BR","Pyrus",1000,3)) 
allCards.push(new CardData(5,"Fury: If you have no cards in hand, +20 [Damage Rating].","Evo","Hyper Howlkor Ultra","BR","Pyrus",1500,5)) 
allCards.push(new CardData(6,"","Evo","[Diamond] Mantonoid","BR","Ventus",1300,6)) 
allCards.push(new CardData(4,"When this opens, you may swap one of this Bakugan's BakuCores with the opposing Bakugan.","Evo","[Diamond] Turtonium","BR","Ventus",800,10)) 
allCards.push(new CardData(8,"","Evo","[Diamond] Webam","BR","Ventus",1500,15)) 
allCards.push(new CardData(1,"Turbo: If you have the most Energy cards in play, +5 [DamageRating].","Evo","Hyper Garganoid Ultra","BR","Ventus",500,4)) 
allCards.push(new CardData(3,"When you play this, give a Bakugan -4 [Damage Rating].","Evo","Hyper Krakelios Ultra","BR","Ventus",600,9)) 
allCards.push(new CardData(3,"[FT]: +6 [Damage Rating].","Evo","Hyper Serpenteze","BR","Ventus",900,4)) 
allCards.push(new CardData(2,"When this opens, you may recharge up to two Energy cards.","Evo","Hyper Serpenteze Ultra","BR","Ventus",700,6)) 
allCards.push(new CardData(2,"Victor: You may Energize a card from your hand uncharged.","Evo","Hyper Trox Ultra","BR","Ventus",700,5)) 
allCards.push(new CardData(7,"You may Reroll once each turn if you miss a Roll with it.","Evo","Maximus Gorthion","BR","Ventus",1000,12)) 
allCards.push(new CardData(5,"When you play this, give a Bakugan -800 [B].","Evo","Maximus Gorthion Ultra","BR","Ventus",900,8)) 
allCards.push(new CardData(7,"You may Reroll this any time you miss a Roll with it.","Evo","Maximus Webam Ultra","BR","Ventus",1200,14)) 
allCards.push(new CardData(4,"[FT] or [SD]: +1000 [B] and +10 [Damage Rating].","Evo","Titan Fangzor Ultra","BR","Ventus",200,2)) 
allCards.push(new CardData(5,"This has +100 [B] for each Energy card you have in play.","Evo","Titan Garganoid Ultra","BR","Ventus",0,9)) 
allCards.push(new CardData(5,"When this opens, you may recharge all of your Energy cards.","Evo","Titan Serpenteze Ultra","BR","Ventus",1000,7)) 
allCards.push(new CardData(5,"Victor: You may Energize any number of cards in your hand uncharged. If you control Wynton Styles, this gets +1000 [B] and +10 [DamageRating].","Evo","Titan Trox Ultra","BR","Ventus",1000,10)) 
allCards.push(new CardData(4,"When this opens, you may swap one of this Bakugan's BakuCores with the opposing Bakugan.","Evo","Hyper Turtonium Ultra","BR","Ventus",800,10)) 
allCards.push(new CardData(5,"","Evo","[Diamond] Hydorous","BB","Aquos",1000,5)) 
allCards.push(new CardData(9,"","Evo","[Diamond] Hydorous Ultra","BB","Aquos",1500,8)) 
allCards.push(new CardData(6,"[SD]: +5 [Damage Rating]. [FT]: +500 [B].","Evo","[Diamond] Serpenteze","BB","Aquos",1000,5)) 
allCards.push(new CardData(4,"[SD]: +400 [B] and +8 [Damage Rating].","Evo","Hyper Pegatrix","BB","Aquos",900,3)) 
allCards.push(new CardData(4,"When you play this, draw three cards.","Evo","Hyper Fangzor","BB","Aquos",1000,3)) 
allCards.push(new CardData(3,"When you play an Action on this, it gets +200 [B].","Evo","Hyper Hydorous","BB","Aquos",500,10)) 
allCards.push(new CardData(3,"Victor - You may play an [Aquos] card with cost 4 [Energy] or less for free.","Evo","Hyper Hydorous Ultra","BB","Aquos",700,5)) 
allCards.push(new CardData(2,"","Evo","Hyper Mantonoid Ultra","BB","Aquos",800,4)) 
allCards.push(new CardData(5,"3 [FrostStrike].","Evo","Hyper Serpenteze Ultra","BB","Aquos",500,8)) 
allCards.push(new CardData(1,"","Evo","Hyper Trox","BB","Aquos",400,7)) 
allCards.push(new CardData(8,"Victor - You may play an [Aquos] card for free.","Evo","Maximus Hydorous Ultra","BB","Aquos",1400,6)) 
allCards.push(new CardData(6,"","Evo","Titan Dragonoid","BB","Aquos",1200,6)) 
allCards.push(new CardData(5,"Victor - Copy the next Action you play.","Evo","Titan Garganoid Ultra","BB","Aquos",900,6)) 
allCards.push(new CardData(1,"","Evo","Hyper Dragonoid","BB","Aurelus",600,8)) 
allCards.push(new CardData(2,"[MS]: +6 [Damage Rating].","Evo","Hyper Howlkor Ultra","BB","Aurelus",900,6)) 
allCards.push(new CardData(2,"[HE]: +300 [B] and +3 [Damage Rating].","Evo","Hyper Maxotaur Ultra","BB","Aurelus",700,5)) 
allCards.push(new CardData(3,"If you discard this card, you may play it for free.","Evo","Hyper Nillious","BB","Aurelus",800,8)) 
allCards.push(new CardData(3,"[FT]: +500 [B].","Evo","Hyper Pegatrix","BB","Aurelus",1100,6)) 
allCards.push(new CardData(3,"[FF]: +700 [B].","Evo","Hyper Garganoid Ultra","BB","Aurelus",900,5)) 
allCards.push(new CardData(4,"[SD]: +8 [Damage Rating]","Evo","Titan Fangzor","BB","Aurelus",1300,4)) 
allCards.push(new CardData(6,"3 [FrostStrike], [DoubleStrike], and [ShadowStrike].","Evo","Titan Hydorous","BB","Aurelus",1000,3)) 
allCards.push(new CardData(5,"[SD]: +800 [B].","Evo","[Diamond] Garganoid Ultra","BB","Darkus",700,9)) 
allCards.push(new CardData(7,"","Evo","[Diamond] Nillious","BB","Darkus",1500,8)) 
allCards.push(new CardData(4,"","Evo","Hyper Dragonoid","BB","Darkus",1000,6)) 
allCards.push(new CardData(4,"[ShadowStrike].","Evo","Hyper Fangzor","BB","Darkus",900,5)) 
allCards.push(new CardData(3,"[FT]: +600 [B].","Evo","Hyper Hydorous","BB","Darkus",400,9)) 
allCards.push(new CardData(3,"[FF]: +5 [Damage Rating] and [ShadowStrike].","Evo","Hyper Hydorous Ultra","BB","Darkus",1000,3)) 
allCards.push(new CardData(3,"When you play this, choose a player to discard a card.","Evo","Hyper Trox","BB","Darkus",900,2)) 
allCards.push(new CardData(3,"Victor - You may discard a card for +2 [Damage Rating]. You may use this any number of times.","Evo","Hyper Nillious","BB","Darkus",800,3)) 
allCards.push(new CardData(5,"This has +1 [Damage Rating] for each Flip card in your discard pile.","Evo","Titan Howlkor Ultra","BB","Darkus",1000,1)) 
allCards.push(new CardData(5,"When you discard a card, this gets +400 [B].","Evo","Titan Mantonoid Ultra","BB","Darkus",400,10)) 
allCards.push(new CardData(6,"Victor - You may discard a card for +4 [Damage Rating]. You may use this any number of times.","Evo","Titan Nillious","BB","Darkus",1300,4)) 
allCards.push(new CardData(6,"","Evo","[Diamond] Gorthion Ultra","BB","Haos",1300,6)) 
allCards.push(new CardData(6,"","Evo","[Diamond] Pegatrix","BB","Haos",1200,6)) 
allCards.push(new CardData(4,"Domination: If your Bakugan are holding the most BakuCores, +900 [B].","Evo","Hyper Fangzor","BB","Haos",600,8)) 
allCards.push(new CardData(3,"If you have three or more Heroes in play, +500 [B] and +5 [Damage Rating].","Evo","Hyper Garganoid Ultra","BB","Haos",700,5)) 
allCards.push(new CardData(2,"[MS]: +200 [B]. [FF]: +2 [Damage Rating].","Evo","Hyper Nillious","BB","Haos",500,6)) 
allCards.push(new CardData(2,"Victor - Shuffle a card from your discard pile into your deck.","Evo","Hyper Hydorous Ultra","BB","Haos",500,6)) 
allCards.push(new CardData(2,"[SD]: +7 [Damage Rating].","Evo","Hyper Serpenteze Ultra","BB","Haos",700,3)) 
allCards.push(new CardData(7,"Victor - Shuffle three cards from your discard pile into your deck.","Evo","Maximus Hydorous Ultra","BB","Haos",1000,8)) 
allCards.push(new CardData(5,"[HE]: +6 [Damage Rating].","Evo","Titan Howlkor Ultra","BB","Haos",1300,5)) 
allCards.push(new CardData(4,"[MS]: +200 [B] and you may attach an additional BakuCore from the Field to Titan Haos Nillious. [FF]: +4 [Damage Rating].","Evo","Titan Nillious","BB","Haos",800,8)) 
allCards.push(new CardData(4,"[FT]: +500 [B] and +5 [Damage Rating].","Evo","Titan Pegatrix","BB","Haos",1000,4)) 
allCards.push(new CardData(6,"[FF]: +500 [B] and +5 [Damage Rating].","Evo","[Diamond] Dragonoid","BB","Pyrus",900,9)) 
allCards.push(new CardData(6,"","Evo","[Diamond] Fangzor","BB","Pyrus",1200,6)) 
allCards.push(new CardData(3,"When you play an Action on this, it gets +2 [Damage Rating].","Evo","Hyper Hydorous","BB","Pyrus",800,4)) 
allCards.push(new CardData(2,"","Evo","Hyper Hydorous Ultra","BB","Pyrus",600,6)) 
allCards.push(new CardData(4,"[FF]: +10 [Damage Rating].","Evo","Hyper Maxotaur Ultra","BB","Pyrus",900,4)) 
allCards.push(new CardData(2,"Victor: +2 [Energy].","Evo","Hyper Trox","BB","Pyrus",600,2)) 
allCards.push(new CardData(1,"[FF]: +300 [B] and +3 [Damage Rating].","Evo","Hyper Dragonoid","BB","Pyrus",400,6)) 
allCards.push(new CardData(3,"","Evo","Hyper Mantonoid Ultra","BB","Pyrus",800,5)) 
allCards.push(new CardData(2,"Fury - If you have no cards in hand, +5 [Damage Rating] and +1000 [B].","Evo","Hyper Serpenteze Ultra","BB","Pyrus",500,7)) 
allCards.push(new CardData(5,"[FT]: +2 [Damage Rating] and [DoubleStrike].","Evo","Titan Fangzor","BB","Pyrus",800,3)) 
allCards.push(new CardData(6,"Victor - Destroy an enemy Energy card.","Evo","Titan Hydorous Ultra","BB","Pyrus",700,7)) 
allCards.push(new CardData(5,"[Double Strike]. If you control Dan Kouzo, +2000 [B].","Evo","Titan Dragonoid","BB","Pyrus",1000,6)) 
allCards.push(new CardData(10,"","Evo","[Diamond] Maxotaur Ultra","BB","Ventus",1500,15)) 
allCards.push(new CardData(3,"Victor - You may Energize the top card of your deck uncharged.","Evo","[Diamond] Trox","BB","Ventus",700,3)) 
allCards.push(new CardData(5,"","Evo","[Diamond] Trox Ultra","BB","Ventus",1400,8)) 
allCards.push(new CardData(3,"[HE]: +400 [B]. Victor - draw a card.","Evo","Hyper Dragonoid","BB","Ventus",400,6)) 
allCards.push(new CardData(2,"When this opens, opposing Bakugan get -3 [Damage Rating].","Evo","Hyper Fangzor","BB","Ventus",400,6)) 
allCards.push(new CardData(4,"Turbo - If you have the most Energy cards, +2 [Damage Rating] and +200 [B].","Evo","Hyper Nillious","BB","Ventus",900,5)) 
allCards.push(new CardData(3,"[MS]: +1000 [B].","Evo","Hyper Pegatrix","BB","Ventus",600,6)) 
allCards.push(new CardData(4,"This gets +1 [Damage Rating] for each Energy card you have in play.", "Evo","Hyper Mantonoid Ultra","BB","Ventus",1000,1)) 
allCards.push(new CardData(6,"","Evo","Titan Howlkor Ultra","BB","Ventus",1200,8)) 
allCards.push(new CardData(4,"","Evo","Titan Maxotaur Ultra","BB","Ventus",800,8)) 
allCards.push(new CardData(5,"Victor - You may Energize the top two cards of your deck uncharged.","Evo","Titan Trox","BB","Ventus",1000,4)) 
allCards.push(new CardData(0,"","Character","Cloptor Ultra","BR","Aquos",600,1,"[FT]","[FT]")) 
allCards.push(new CardData(0,"[MS] or [FF]: +600 [B].","Character","Cubbo","BR","Aquos",100,5,"[MS]","[FF]")) 
allCards.push(new CardData(0,"Victor: Draw two cards.","Character","Fangzor Ultra","BR","Aquos",200,4,"[FT]","[HE]")) 
allCards.push(new CardData(0,"Victor: Draw a card.","Character","Gorthion","BR","Aquos",300,1,"[SD]","[FF]")) 
allCards.push(new CardData(0,"","Character","Gorthion Ultra","BR","Aquos",400,3,"[MS]","[HE]")) 
allCards.push(new CardData(0,"","Character","Hydranoid","BR","Aquos",300,6,"[SD]","[SD]")) 
allCards.push(new CardData(0,"[FT]: +200 [B].","Character","Hydranoid Ultra","BR","Aquos",700,1,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Mantonoid","BR","Aquos",400,3,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Nobilious Ultra","BR","Aquos",500,3,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Pegatrix Ultra","BR","Aquos",600,1,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Pyravian Ultra","BR","Aquos",400,2,"[MS]","[MS]")) 
allCards.push(new CardData(0,"","Character","Trhyno","BR","Aquos",300,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[HE]: +100 [B] and +3 [Damage Rating]. You may Reroll this once each turn if you miss a Roll with it.","Character","Turtonium Ultra","BR","Aquos",500,2,"[FT]","[HE]")) 
allCards.push(new CardData(0,"","Character","Vicerox","BR","Aquos",200,7,"[SD]","[FF]")) 
allCards.push(new CardData(0,"","Character","Webam Ultra","BR","Aquos",400,5,"[SD]","[SD]")) 
allCards.push(new CardData(0,"You may Reroll this once each turn if you miss a roll with it.","Character","Cubbo","BR","Aurelus",200,7,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Dragonoid Ultra","BR","Aurelus",500,4,"[MS]","[FF]")) 
allCards.push(new CardData(0,"","Character","Gorthion Ultra","BR","Aurelus",500,4,"[SD]","[HE]")) 
allCards.push(new CardData(0,"[FF]: +1000 [B].","Character","Hydranoid Ultra","BR","Aurelus",200,2,"[FF]","[FF]")) 
allCards.push(new CardData(0,"You may Reroll this once each turn if you miss a roll with it.","Character","Krakelios Ultra","BR","Aurelus",600,2,"[MS]","[FT]")) 
allCards.push(new CardData(0,"[HE]: +2 [FrostStrike].","Character","Lupitheon Ultra","BR","Aurelus",400,5,"[HE]","[HE]")) 
allCards.push(new CardData(0,"","Character","Nobilious Ultra","BR","Aurelus",500,5,"[FT]","[HE]")) 
allCards.push(new CardData(0,"[FT]: +4 [Damage Rating].","Character","Phaedrus Ultra","BR","Aurelus",700,1,"[FF]","[FT]")) 
allCards.push(new CardData(0,"[SD]: +400 [B].","Character","Trhyno","BR","Aurelus",300,5,"[SD]","[SD]")) 
allCards.push(new CardData(0,"When you play an Action card on this, this gets +100 [B] and +2 [Damage Rating].","Character","Trox","BR","Aurelus",300,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[MS]: +[ShadowStrike].","Character","Vicerox","BR","Aurelus",300,6,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Vicerox Ultra","BR","Aurelus",400,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Zentaur","BR","Aurelus",400,6,"[SD]","[FF]")) 
allCards.push(new CardData(0,"","Character","Cubbo","BR","Darkus",200,7,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Cyndeous","BR","Darkus",400,4,"[FF]","[HE]")) 
allCards.push(new CardData(0,"[FT]: +300 [B] and +2 [Damage Rating].","Character","Dragonoid Ultra","BR","Darkus",300,3,"[FT]","[FT]")) 
allCards.push(new CardData(0,"[ShadowStrike].","Character","Gorthion","BR","Darkus",100,8,"[MS]","[HE]")) 
allCards.push(new CardData(0,"","Character","Gorthion Ultra","BR","Darkus",400,3,"[SD]","[MS]")) 
allCards.push(new CardData(0,"","Character","Hydranoid Ultra","BR","Darkus",500,3,"[HE]","[HE]")) 
allCards.push(new CardData(0,"[HE]: +200 [B].","Character","Krakelios Ultra","BR","Darkus",600,1,"[HE]","[HE]")) 
allCards.push(new CardData(0,"Victor: All players must discard a card.","Character","Lupitheon Ultra","BR","Darkus",500,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"You may Reroll this once each turn if you miss a Roll with it.","Character","Mantonoid","BR","Darkus",200,6,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Phaedrus","BR","Darkus",300,5,"[MS]","[HE]")) 
allCards.push(new CardData(0,"","Character","Serpenteze Ultra","BR","Darkus",300,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Skorporos","BR","Darkus",400,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Skorporos Ultra","BR","Darkus",700,1,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Trhyno","BR","Darkus",300,4,"[SD]","[FF]")) 
allCards.push(new CardData(0,"","Character","Webam Ultra","BR","Darkus",400,3,"[SD]","[HE]")) 
allCards.push(new CardData(0,"[MS]: +5 [Damage Rating].","Character","Zentaur","BR","Darkus",200,4,"[MS]","[FT]")) 
allCards.push(new CardData(0,"[FT] or [SD]: +2 [FrostStrike].","Character","Cubbo","BR","Haos",300,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Gorthion","BR","Haos",200,7,"[FT]","[FT]")) 
allCards.push(new CardData(0,"Domination: If your Bakugan are holding the most BakuCores +4 [Damage Rating].","Character","Lupitheon Ultra","BR","Haos",400,2,"[SD]","[FT]")) 
allCards.push(new CardData(0,"Victor: You may attach a [FT] to this Bakugan.","Character","Nobilious Ultra","BR","Haos",600,1,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Pandoxx Ultra","BR","Haos",700,2,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Pegatrix Ultra","BR","Haos",300,5,"[MS]","[SD]")) 
allCards.push(new CardData(0,"","Character","Phaedrus","BR","Haos",300,6,"[FF]","[SD]")) 
allCards.push(new CardData(0,"","Character","Trhyno","BR","Haos",300,4,"[HE]","[HE]")) 
allCards.push(new CardData(0,"[FF]: +600 [B].","Character","Turtonium","BR","Haos",200,5,"[FF]","[FF]")) 
allCards.push(new CardData(0,"","Character","Vicerox","BR","Haos",300,5,"[MS]","[MS]")) 
allCards.push(new CardData(0,"1 [FrostStrike].","Character","Vicerox Ultra","BR","Haos",500,1,"[FF]","[FT]")) 
allCards.push(new CardData(0,"","Character","Artulean Ultra","BR","Pyrus",400,2,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Cyndeous","BR","Pyrus",200,6,"[SD]","[SD]")) 
allCards.push(new CardData(0,"Fury: If you have no cards in hand, +9 [Damage Rating].","Character","Hydranoid Ultra","BR","Pyrus",600,1,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Mantonoid","BR","Pyrus",500,2,"[SD]","[HE]")) 
allCards.push(new CardData(0,"[DoubleStrike].","Character","Nillious","BR","Pyrus",100,3,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[HE]: +200 [B] and [DoubleStrike].","Character","Nillious Ultra","BR","Pyrus",200,3,"[HE]","[HE]")) 
allCards.push(new CardData(0,"[MS] or [FF]: +200 [B].","Character","Nobilious Ultra","BR","Pyrus",500,2,"[MS]","[FF]")) 
allCards.push(new CardData(0,"","Character","Pegatrix","BR","Pyrus",300,4,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Phaedrus","BR","Pyrus",300,5,"[FF]","[FF]")) 
allCards.push(new CardData(0,"","Character","Serpenteze","BR","Pyrus",600,1,"[FF]","[FT]")) 
allCards.push(new CardData(0,"","Character","Trhyno","BR","Pyrus",300,4,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Trox Ultra","BR","Pyrus",300,3,"[MS]","[FF]")) 
allCards.push(new CardData(0,"You may Reroll this once each turn if you miss a roll with it.","Character","Turtonium Ultra","BR","Pyrus",400,2,"[FF]","[HE]")) 
allCards.push(new CardData(0,"Fury: If you have no cards in hand, +800 [B].","Character","Vicerox","BR","Pyrus",200,5,"[FT]","[HE]")) 
allCards.push(new CardData(0,"","Character","Vicerox Ultra","BR","Pyrus",500,5,"[MS]","[HE]")) 
allCards.push(new CardData(0,"","Character","Cubbo","BR","Ventus",300,6,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[MS]: +4 [Damage Rating].","Character","Cyndeous","BR","Ventus",200,7,"[MS]","[SD]")) 
allCards.push(new CardData(0,"","Character","Hydranoid Ultra","BR","Ventus",600,1,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Lupitheon Ultra","BR","Ventus",500,3,"[SD]","[HE]")) 
allCards.push(new CardData(0,"[FF]: +300 [B].","Character","Phaedrus","BR","Ventus",300,5,"[FF]","[HE]")) 
allCards.push(new CardData(0,"[ShadowStrike].","Character","Phaedrus Ultra","BR","Ventus",400,4,"[FF]","[FT]")) 
allCards.push(new CardData(0,"","Character","Skorporos Ultra","BR","Ventus",400,5,"[FT]","[FT]")) 
allCards.push(new CardData(0,"[HE]: +100 [B] and +2 [Damage Rating].","Character","Turtonium","BR","Ventus",500,2,"[HE]","[HE]")) 
allCards.push(new CardData(0,"","Character","Turtonium Ultra","BR","Ventus",400,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[HE]: +200 [B] and +2 [Damage Rating].","Character","Vicerox Ultra","BR","Ventus",500,2,"[HE]","[HE]")) 
allCards.push(new CardData(0,"You may Reroll this once each turn if you miss a Roll with it.","Character","Webam Ultra","BR","Ventus",400,4,"[MS]","[FT]")) 
allCards.push(new CardData(0,"[FT]: +300 [B].","Character","Phaedrus","BR","Aquos",200,8,"[FT]","[FT]")) 
allCards.push(new CardData(0,"[SD]: +3 [Damage Rating].","Character","Vicerox","BR","Ventus",600,2,"[SD]","[SD]")) 
allCards.push(new CardData(0,"1 [FrostStrike].","Character","Cyndeous Ultra","BB","Aquos",300,4,"[FT]","[HE]")) 
allCards.push(new CardData(0,"","Character","Dragonoid","BB","Aquos",400,3,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Fangzor","BB","Aquos",600,1,"[FF]","[FT]")) 
allCards.push(new CardData(0,"","Character","Garganoid Ultra","BB","Aquos",300,5,"[FF]","[HE]")) 
allCards.push(new CardData(0,"","Character","Krakelios Ultra","BB","Haos",400,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Hydorous","BB","Aquos",200,6,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Hydorous Ultra","BB","Aquos",400,4,"[SD]","[SD]")) 
allCards.push(new CardData(0,"[FT]: +200 [B].","Character","Krakelios Ultra","BB","Aquos",500,1,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Mantonoid Ultra","BB","Aquos",400,3,"[MS]","[FT]")) 
allCards.push(new CardData(0,"[MS]: +200 [B] and +2 [FrostStrike].","Character","Nillious","BB","Aquos",300,4,"[MS]","[SD]")) 
allCards.push(new CardData(0,"[SD]: +100 [B] and +3 [Damage Rating].","Character","Pegatrix","BB","Aquos",500,2,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Serpenteze","BB","Aquos",300,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"2 [FrostStrike].","Character","Serpenteze Ultra","BB","Aquos",100,5,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Trox","BB","Aquos",200,7,"[MS]","[SD]")) 
allCards.push(new CardData(0,"[SD]: +2 [FrostStrike]","Character","Turtonium","BB","Aquos",500,2,"[SD]","[SD]")) 
allCards.push(new CardData(0,"[FT]: +200 [B] and +2 [Damage Rating].","Character","Trox Ultra","BB","Aquos",400,4,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Dragonoid","BB","Aurelus",400,6,"[MS]","[FF]")) 
allCards.push(new CardData(0,"[SD]: +5 [Damage Rating].","Character","Fangzor","BB","Aurelus",700,2,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Fangzor Ultra","BB","Aurelus",700,3,"[SD]","[FF]")) 
allCards.push(new CardData(0,"[FF]: +400 [B].","Character","Garganoid Ultra","BB","Aurelus",700,3,"[FF]","[FT]")) 
allCards.push(new CardData(0,"[MS]: +4 [Damage Rating].","Character","Howlkor Ultra","BB","Aurelus",500,5,"[MS]","[SD]")) 
allCards.push(new CardData(0,"","Character","Hydorous","BB","Aurelus",400,5,"[HE]","[HE]")) 
allCards.push(new CardData(0,"","Character","Hydorous Ultra","BB","Aurelus",200,2,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Mantonoid","BB","Aurelus",300,1,"[MS]","[SD]")) 
allCards.push(new CardData(0,"[HE]: +200 [B] and +2 [Damage Rating].","Character","Maxotaur Ultra","BB","Aurelus",600,1,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Nillious","BB","Aurelus",500,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[FT]: +300 [B].","Character","Pegatrix","BB","Aurelus",600,4,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Trox Ultra","BB","Aurelus",800,1,"[HE]","[HE]")) 
allCards.push(new CardData(0,"[MS] : +[ShadowStrike]. [FF]: +2 [FrostStrike].","Character","Turtonium","BB","Aurelus",200,6,"[MS]","[FF]")) 
allCards.push(new CardData(0,"Victor - Your opponent discards a card.","Character","Cyndeous Ultra","BB","Darkus",300,1,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Dragonoid","BB","Darkus",400,4,"[FF]","[SD]")) 
allCards.push(new CardData(0,"[ShadowStrike].","Character","Fangzor","BB","Darkus",400,3,"[FT]","[FT]")) 
allCards.push(new CardData(0,"[ShadowStrike].","Character","Fangzor Ultra","BB","Darkus",600,1,"[MS]","[SD]")) 
allCards.push(new CardData(0,"","Character","Garganoid Ultra","BB","Darkus",300,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Krakelios Ultra","BB","Ventus",600,2,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Howlkor Ultra","BB","Darkus",300,2,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Hydorous","BB","Darkus",300,4,"[FT]","[FT]")) 
allCards.push(new CardData(0,"[FF]: +3 [Damage Rating].","Character","Hydorous Ultra","BB","Darkus",800,1,"[FF]","[FT]")) 
allCards.push(new CardData(0,"","Character","Mantonoid Ultra","BB","Darkus",300,4,"[MS]","[SD]")) 
allCards.push(new CardData(0,"","Character","Nillious","BB","Darkus",500,2,"[FT]","[HE]")) 
allCards.push(new CardData(0,"[SD]: +400 [B].","Character","Nillious Ultra","BB","Darkus",200,6,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Pegatrix","BB","Darkus",200,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[FF]: +200 [B] and +3 [Damage Rating].","Character","Serpenteze","BB","Darkus",400,3,"[FF]","[FT]")) 
allCards.push(new CardData(0,"","Character","Trox","BB","Darkus",700,1,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Turtonium Ultra","BB","Darkus",500,3,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Dragonoid","BB","Haos",400,3,"[FT]","[HE]")) 
allCards.push(new CardData(0,"Domination: If your Bakugan are holding the most BakuCores, +400 [B].","Character","Fangzor","BB","Haos",100,7,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Garganoid Ultra","BB","Haos",400,3,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Gorthion Ultra","BB","Haos",600,2,"[MS]","[SD]")) 
allCards.push(new CardData(0,"[HE]: +4 [Damage Rating].","Character","Howlkor Ultra","BB","Haos",300,4,"[HE]","[HE]")) 
allCards.push(new CardData(0,"1 [FrostStrike]","Character","Hydorous","BB","Haos",200,3,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Hydorous Ultra","BB","Haos",200,4,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Mantonoid","BB","Haos",500,2,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Mantonoid Ultra","BB","Haos",500,3,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Maxotaur Ultra","BB","Haos",100,7,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Nillious","BB","Haos",300,5,"[MS]","[FF]")) 
allCards.push(new CardData(0,"","Character","Nillious Ultra","BB","Haos",400,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[FT]: +200 [B] and +2 [Damage Rating].","Character","Pegatrix","BB","Haos",500,2,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Serpenteze","BB","Haos",300,3,"[FF]","[SD]")) 
allCards.push(new CardData(0,"[SD]: +4 [Damage Rating].","Character","Serpenteze Ultra","BB","Haos",500,1,"[SD]","[SD]")) 
allCards.push(new CardData(0,"[MS]: +3 [FrostStrike].","Character","Trox","BB","Haos",300,3,"[MS]","[HE]")) 
allCards.push(new CardData(0,"","Character","Dragonoid","BB","Pyrus",200,5,"[FF]","[FT]")) 
allCards.push(new CardData(0,"[FT]: +1 [Damage Rating] and [DoubleStrike].","Character","Fangzor","BB","Pyrus",400,1,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Fangzor Ultra","BB","Pyrus",400,4,"[HE]","[HE]")) 
allCards.push(new CardData(0,"","Character","Garganoid Ultra","BB","Pyrus",300,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[FT]: +100 [B] and +2 [Damage Rating].","Character","Gorthion","BB","Pyrus",200,4,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Gorthion Ultra","BB","Pyrus",400,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Howlkor Ultra","BB","Pyrus",100,2,"[MS]","[MS]")) 
allCards.push(new CardData(0,"","Character","Hydorous","BB","Pyrus",400,3,"[MS]","[SD]")) 
allCards.push(new CardData(0,"","Character","Hydorous Ultra","BB","Pyrus",300,5,"[SD]","[HE]")) 
allCards.push(new CardData(0,"[SD]: +200 [B].","Character","Cyndeous Ultra","BB","Pyrus",200,6,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Mantonoid Ultra","BB","Pyrus",600,2,"[FT]","[FT]")) 
allCards.push(new CardData(0,"[FF]: +2 [Damage Rating].","Character","Maxotaur Ultra","BB","Pyrus",100,4,"[FF]","[FT]")) 
allCards.push(new CardData(0,"","Character","Serpenteze Ultra","BB","Pyrus",300,5,"[FF]","[FT]")) 
allCards.push(new CardData(0,"Victor: +1 [Energy].","Character","Trox","BB","Pyrus",500,1,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Dragonoid Ultra","BB","Pyrus",500,5,"[MS]","[FF]")) 
allCards.push(new CardData(0,"","Character","Gorthion Ultra","BB","Ventus",200,4,"[FF]","[FT]")) 
allCards.push(new CardData(0,"[HE]: +400 [B].","Character","Dragonoid","BB","Ventus",200,4,"[HE]","[HE]")) 
allCards.push(new CardData(0,"When this opens, opposing Bakugan get -1 [Damage Rating].","Character","Fangzor","BB","Ventus",300,3,"[SD]","[FF]")) 
allCards.push(new CardData(0,"[SD] or [FT]: +500 [B] and +5 [Damage Rating].","Character","Fangzor Ultra","BB","Ventus",100,1,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Garganoid Ultra","BB","Ventus",400,3,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Gorthion","BB","Ventus",300,6,"[SD]","[SD]")) 
allCards.push(new CardData(0,"","Character","Howlkor Ultra","BB","Ventus",500,2,"[SD]","[FF]")) 
allCards.push(new CardData(0,"","Character","Mantonoid","BB","Ventus",500,2,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Mantonoid Ultra","BB","Ventus",600,1,"[FT]","[HE]")) 
allCards.push(new CardData(0,"","Character","Maxotaur Ultra","BB","Ventus",300,5,"[SD]","[FT]")) 
allCards.push(new CardData(0,"","Character","Nillious","BB","Ventus",400,4,"[SD]","[FT]")) 
allCards.push(new CardData(0,"[MS]: +200 [B].","Character","Pegatrix","BB","Ventus",300,4,"[MS]","[SD]")) 
allCards.push(new CardData(0,"[FT]: +4 [Damage Rating].","Character","Serpenteze","BB","Ventus",600,2,"[FT]","[FT]")) 
allCards.push(new CardData(0,"","Character","Serpenteze Ultra","BB","Ventus",400,3,"[MS]","[FT]")) 
allCards.push(new CardData(0,"","Character","Trox","BB","Ventus",500,1,"[MS]","[HE]")) 
allCards.push(new CardData(0,"Victor - You may energize a card in your hand uncharged.","Character","Trox Ultra","BB","Ventus",300,1,"[SD]","[HE]")) 
allCards.push(new CardData(0,"","Character","Serpenteze","BB","Aurelus",300,7,"[SD]","[FT]")) 


client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`)
})

client.on('message', msg => {
var target = -1
  if (msg.content.startsWith('!search')) {
	for(var i=0;i<allCards.length;i++)
	{
	if(allCards[i].name.toLowerCase().includes(msg.content.substr(8).toLowerCase()))
	{
		target = i
		break
	}
	}
	if(target!=-1)
{
	if(allCards[target].type !="Evo" && allCards[target].type!="Character")
{
    	msg.channel.send({embed: {
      		color: 3447003,
      		title: allCards[target].name,
      		fields: [
        { name: allCards[target].attribute, value: "Type: " + allCards[target].type + "\nText: " + allCards[target].text, inline: true},
      ]
    }
  });
}
	else if(allCards[target].type == "Evo")
{
    	msg.channel.send({embed: {
      		color: 3447003,
      		title: allCards[target].name,
      		fields: [
        { name: allCards[target].attribute, value: "Type: " + allCards[target].type + "\nText: " + allCards[target].text + "\nB-Power: " + allCards[target].B + "\nDamage Rating: " + allCards[target].Dmg, inline: true},
      ]
    }
  });
}
else if(allCards[target].type == "Character")
{
    	msg.channel.send({embed: {
      		color: 3447003,
      		title: allCards[target].name,
      		fields: [
        { name: allCards[target].attribute, value: "Type: " + allCards[target].type + "\nText: " + allCards[target].text + "\nB-Power: " + allCards[target].B + "\nDamage Rating: " + allCards[target].Dmg + "\nCore1: " + allCards[target].Core1 + "\nCore2: " + allCards[target].Core2, inline: true},
      ]
    }
  });
}
}
  }
})

client.login('NjAzNzA3Nzk2MDU5NDU1NjU5.XTjVHQ.PXKAKgQL5UHDUzCfmRy8tXSGH34')